# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'materialCalculationView.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QLineEdit,
    QListWidget, QListWidgetItem, QMainWindow, QMenuBar,
    QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1024, 768)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.imageWidget = QWidget(self.centralwidget)
        self.imageWidget.setObjectName(u"imageWidget")
        self.imageWidget.setGeometry(QRect(30, 30, 400, 300))
        self.image_Label = QLabel(self.imageWidget)
        self.image_Label.setObjectName(u"image_Label")
        self.image_Label.setGeometry(QRect(0, 0, 400, 300))
        self.specWidget = QWidget(self.centralwidget)
        self.specWidget.setObjectName(u"specWidget")
        self.specWidget.setGeometry(QRect(30, 330, 400, 350))
        self.styleWidget = QWidget(self.specWidget)
        self.styleWidget.setObjectName(u"styleWidget")
        self.styleWidget.setGeometry(QRect(0, 0, 400, 80))
        self.label_2 = QLabel(self.styleWidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(0, 0, 150, 40))
        font = QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_3 = QLabel(self.styleWidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(0, 40, 150, 40))
        self.label_3.setFont(font)
        self.label_3.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.material_ComboBox = QComboBox(self.styleWidget)
        self.material_ComboBox.setObjectName(u"material_ComboBox")
        self.material_ComboBox.setGeometry(QRect(150, 5, 200, 30))
        self.material_ComboBox.setFont(font)
        self.style_ComboBox = QComboBox(self.styleWidget)
        self.style_ComboBox.setObjectName(u"style_ComboBox")
        self.style_ComboBox.setGeometry(QRect(150, 45, 200, 30))
        self.style_ComboBox.setFont(font)
        self.specTypeA = QWidget(self.specWidget)
        self.specTypeA.setObjectName(u"specTypeA")
        self.specTypeA.setGeometry(QRect(0, 80, 400, 120))
        self.typeA_ComboBox_1 = QComboBox(self.specTypeA)
        self.typeA_ComboBox_1.setObjectName(u"typeA_ComboBox_1")
        self.typeA_ComboBox_1.setGeometry(QRect(150, 5, 200, 30))
        self.typeA_ComboBox_1.setFont(font)
        self.typeA_LineEdit_1 = QLineEdit(self.specTypeA)
        self.typeA_LineEdit_1.setObjectName(u"typeA_LineEdit_1")
        self.typeA_LineEdit_1.setGeometry(QRect(150, 45, 200, 30))
        self.typeA_LineEdit_1.setFont(font)
        self.typeA_Label_1 = QLabel(self.specTypeA)
        self.typeA_Label_1.setObjectName(u"typeA_Label_1")
        self.typeA_Label_1.setGeometry(QRect(0, 0, 150, 40))
        self.typeA_Label_1.setFont(font)
        self.typeA_Label_1.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.typeA_Label_2 = QLabel(self.specTypeA)
        self.typeA_Label_2.setObjectName(u"typeA_Label_2")
        self.typeA_Label_2.setGeometry(QRect(0, 40, 150, 40))
        self.typeA_Label_2.setFont(font)
        self.typeA_Label_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.typeA_LineEdit_1.raise_()
        self.typeA_ComboBox_1.raise_()
        self.typeA_Label_1.raise_()
        self.typeA_Label_2.raise_()
        self.label_4 = QLabel(self.specWidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(0, 200, 150, 40))
        self.label_4.setFont(font)
        self.label_4.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.density_Label = QLabel(self.specWidget)
        self.density_Label.setObjectName(u"density_Label")
        self.density_Label.setGeometry(QRect(150, 205, 200, 30))
        self.density_Label.setFont(font)
        self.density_Label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.specTypeB = QWidget(self.specWidget)
        self.specTypeB.setObjectName(u"specTypeB")
        self.specTypeB.setGeometry(QRect(0, 80, 400, 120))
        self.typeB_ComboBox_2 = QComboBox(self.specTypeB)
        self.typeB_ComboBox_2.setObjectName(u"typeB_ComboBox_2")
        self.typeB_ComboBox_2.setGeometry(QRect(150, 45, 200, 30))
        self.typeB_ComboBox_2.setFont(font)
        self.typeB_ComboBox_1 = QComboBox(self.specTypeB)
        self.typeB_ComboBox_1.setObjectName(u"typeB_ComboBox_1")
        self.typeB_ComboBox_1.setGeometry(QRect(150, 5, 200, 30))
        self.typeB_ComboBox_1.setFont(font)
        self.typeB_LineEdit_1 = QLineEdit(self.specTypeB)
        self.typeB_LineEdit_1.setObjectName(u"typeB_LineEdit_1")
        self.typeB_LineEdit_1.setGeometry(QRect(150, 85, 200, 30))
        self.typeB_LineEdit_1.setFont(font)
        self.typeB_Label_1 = QLabel(self.specTypeB)
        self.typeB_Label_1.setObjectName(u"typeB_Label_1")
        self.typeB_Label_1.setGeometry(QRect(0, 0, 150, 40))
        self.typeB_Label_1.setFont(font)
        self.typeB_Label_1.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.typeB_Label_2 = QLabel(self.specTypeB)
        self.typeB_Label_2.setObjectName(u"typeB_Label_2")
        self.typeB_Label_2.setGeometry(QRect(0, 40, 150, 40))
        self.typeB_Label_2.setFont(font)
        self.typeB_Label_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.typeB_Label_3 = QLabel(self.specTypeB)
        self.typeB_Label_3.setObjectName(u"typeB_Label_3")
        self.typeB_Label_3.setGeometry(QRect(0, 80, 150, 40))
        self.typeB_Label_3.setFont(font)
        self.typeB_Label_3.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.specTypeC = QWidget(self.specWidget)
        self.specTypeC.setObjectName(u"specTypeC")
        self.specTypeC.setGeometry(QRect(0, 80, 400, 120))
        self.typeC_ComboBox_1 = QComboBox(self.specTypeC)
        self.typeC_ComboBox_1.setObjectName(u"typeC_ComboBox_1")
        self.typeC_ComboBox_1.setGeometry(QRect(150, 5, 200, 30))
        self.typeC_ComboBox_1.setFont(font)
        self.typeC_LineEdit_2 = QLineEdit(self.specTypeC)
        self.typeC_LineEdit_2.setObjectName(u"typeC_LineEdit_2")
        self.typeC_LineEdit_2.setGeometry(QRect(150, 85, 200, 30))
        self.typeC_LineEdit_2.setFont(font)
        self.typeC_Label_1 = QLabel(self.specTypeC)
        self.typeC_Label_1.setObjectName(u"typeC_Label_1")
        self.typeC_Label_1.setGeometry(QRect(0, 0, 150, 40))
        self.typeC_Label_1.setFont(font)
        self.typeC_Label_1.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.typeC_Label_2 = QLabel(self.specTypeC)
        self.typeC_Label_2.setObjectName(u"typeC_Label_2")
        self.typeC_Label_2.setGeometry(QRect(0, 40, 150, 40))
        self.typeC_Label_2.setFont(font)
        self.typeC_Label_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.typeC_Label_3 = QLabel(self.specTypeC)
        self.typeC_Label_3.setObjectName(u"typeC_Label_3")
        self.typeC_Label_3.setGeometry(QRect(0, 80, 150, 40))
        self.typeC_Label_3.setFont(font)
        self.typeC_Label_3.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.typeC_LineEdit_1 = QLineEdit(self.specTypeC)
        self.typeC_LineEdit_1.setObjectName(u"typeC_LineEdit_1")
        self.typeC_LineEdit_1.setGeometry(QRect(150, 45, 200, 30))
        self.typeC_LineEdit_1.setFont(font)
        self.label_5 = QLabel(self.specWidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(0, 240, 150, 40))
        self.label_5.setFont(font)
        self.label_5.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_6 = QLabel(self.specWidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(0, 280, 150, 40))
        self.label_6.setFont(font)
        self.label_6.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.unitPrice_Label = QLabel(self.specWidget)
        self.unitPrice_Label.setObjectName(u"unitPrice_Label")
        self.unitPrice_Label.setGeometry(QRect(150, 245, 200, 30))
        self.unitPrice_Label.setFont(font)
        self.unitPrice_Label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.total_Label = QLabel(self.specWidget)
        self.total_Label.setObjectName(u"total_Label")
        self.total_Label.setGeometry(QRect(150, 285, 200, 30))
        self.total_Label.setFont(font)
        self.total_Label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.styleWidget.raise_()
        self.label_4.raise_()
        self.density_Label.raise_()
        self.specTypeA.raise_()
        self.specTypeB.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.unitPrice_Label.raise_()
        self.total_Label.raise_()
        self.specTypeC.raise_()
        self.specWidgit = QWidget(self.centralwidget)
        self.specWidgit.setObjectName(u"specWidgit")
        self.specWidgit.setGeometry(QRect(460, 30, 550, 650))
        self.specList = QLabel(self.specWidgit)
        self.specList.setObjectName(u"specList")
        self.specList.setGeometry(QRect(0, 0, 550, 30))
        self.specList.setFont(font)
        self.specList.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.listWidget = QListWidget(self.specWidgit)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setGeometry(QRect(0, 30, 550, 600))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1024, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.image_Label.setText("")
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u6750\u8cea(Material) :", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u6a23\u5f0f(Style) :", None))
        self.typeA_LineEdit_1.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.typeA_Label_1.setText(QCoreApplication.translate("MainWindow", u"\u5916\u5f91(D) :", None))
        self.typeA_Label_2.setText(QCoreApplication.translate("MainWindow", u"\u5167\u5f91(d) :", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u5bc6\u5ea6 :", None))
        self.density_Label.setText("")
        self.typeB_LineEdit_1.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.typeB_Label_1.setText(QCoreApplication.translate("MainWindow", u"\u5916\u5f91(D) :", None))
        self.typeB_Label_2.setText(QCoreApplication.translate("MainWindow", u"\u5167\u5f91(d) :", None))
        self.typeB_Label_3.setText(QCoreApplication.translate("MainWindow", u"\u9577\u5ea6(L) :", None))
        self.typeC_LineEdit_2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.typeC_Label_1.setText(QCoreApplication.translate("MainWindow", u"\u5916\u5f91(D) :", None))
        self.typeC_Label_2.setText(QCoreApplication.translate("MainWindow", u"\u5167\u5f91(d) :", None))
        self.typeC_Label_3.setText(QCoreApplication.translate("MainWindow", u"\u9577\u5ea6(L) :", None))
        self.typeC_LineEdit_1.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u55ae\u50f9 :", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u5408\u8a08(Total) :", None))
        self.unitPrice_Label.setText("")
        self.total_Label.setText("")
        self.specList.setText(QCoreApplication.translate("MainWindow", u"\u898f\u683c\u8868", None))
    # retranslateUi

